{"name": "Создание заказа с неверным хешем ингредиента", "status": "failed", "statusDetails": {"message": "AssertionError: assert 400 == 500\n +  where 400 = <Response [400]>.status_code", "trace": "self = <test_04_create_order.TestCreateOrder object at 0x1022d41d0>\nauth_token = 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MmZiNTA0OWVkMjgwMDAxYjUwZDE1MyIsImlhdCI6MTczMTE3OTc4MCwiZXhwIjoxNzMxMTgwOTgwfQ.sNZQr-vWEL823PcBpf3Zm6SWi__9SZH6LoN0jQ_XQ9w'\n\n    @allure.title(\"Создание заказа с неверным хешем ингредиента\")\n    def test_create_order_invalid_ingredient_hash(self, auth_token):\n        headers = {\"Authorization\": auth_token}\n        order_data = {\"ingredients\": [\"invalid_hash\"]}\n        response = requests.post(DataUrl.BASE_URL + self.endpoint_create_order, headers=headers, json=order_data)\n    \n>       assert response.status_code == 500\nE       assert 400 == 500\nE        +  where 400 = <Response [400]>.status_code\n\ntests/test_04_create_order.py:71: AssertionError"}, "start": 1731179790279, "stop": 1731179791037, "uuid": "a8682c69-034c-48a7-a755-90b27257430f", "historyId": "3def9923f12e024e7bd62c0cc63fa028", "testCaseId": "3def9923f12e024e7bd62c0cc63fa028", "fullName": "tests.test_04_create_order.TestCreateOrder#test_create_order_invalid_ingredient_hash", "labels": [{"name": "story", "value": "4. Создание заказа"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_04_create_order"}, {"name": "subSuite", "value": "TestCreateOrder"}, {"name": "host", "value": "MBP-Vlad"}, {"name": "thread", "value": "8112-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_04_create_order"}]}